name: Trigger Integration Tests

on: push

jobs:
  test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
    - name: install npms
      run: npm install
    - name: run tests
      run: npm test
